List of Customers: [
    'John Smith',      'Alice Johnson',
    'Emily Brown',     'Michael Davis',
    'Sophia Wilson',   'Emma Thompson',
    'Oliver Brown',    'Isabella Garcia',
    'Liam Wilson',     'Charlotte Lee',
    'Daniel Miller',   'Mia Rodriguez',
    'Alexander Brown', 'Amelia Wilson',
    'Benjamin Garcia', 'Ethan Smith',
    'Evelyn Taylor',   'Mason Martinez',
    'Avery Brown',     'Scarlett White'
  ]
  Each Item Order Count: {
    'Pepperoni Pizza': 1,
    'Garlic Bread': 4,
    'Soft Drink': 1,
    Cheeseburger: 2,
    'French Fries': 2,
    Milkshake: 2,
    'California Roll': 3,
    Edamame: 1,
    'Green Tea': 2,
    'Margherita Pizza': 2,
    'Caesar Salad': 2,
    'Iced Tea': 2,
    'Chicken Tikka Masala': 2,
    'Naan Bread': 3,
    'Rice Pilaf': 2,
    'Spaghetti Carbonara': 1,
    Tiramisu: 1,
    'Double Cheeseburger': 2,
    'Onion Rings': 1,
    Soda: 6,
    'Fish and Chips': 1,
    'Cole Slaw': 1,
    Lemonade: 2,
    'Pad Thai Noodles': 2,
    'Spring Rolls': 3,
    'Thai Iced Tea': 2,
    'Caprese Salad': 1,
    'Italian Soda': 2,
    'Sushi Combo': 1,
    'Miso Soup': 5,
    'Green Tea Ice Cream': 1,
    'BBQ Chicken Wings': 3,
    'Loaded Nachos': 1,
    Beer: 2,
    'Philly Cheesesteak': 2,
    Fries: 1,
    'Iced Coffee': 3,
    'Pad Krapow Moo': 2,
    'Tom Yum Soup': 1,
    'Thai Iced Coffee': 2,
    Steak: 1,
    'Baked Potato': 1,
    'Red Wine': 1,
    'Beef Burrito': 2,
    Guacamole: 1,
    'Chicken Alfredo': 1,
    Breadsticks: 2,
    Hamburger: 2,
    'Taco Salad': 1,
    Quesadilla: 1,
    Churros: 2,
    'Chicken Teriyaki': 2,
    'Vegetable Tempura': 1
  }
  Top Selling Item: Soda
  Average Customer Order Price: 34.00
  Total Delivery Persons and Order Status: {
    'Sarah Johnson': { totalOrders: 4, statusCount: { Delivered: 4 } },
    'David Lee': { totalOrders: 4, statusCount: { 'In Transit': 3, Delivered: 1 } },
    '': { totalOrders: 4, statusCount: { '': 4 } },
    'Emily Parker': { totalOrders: 4, statusCount: { Delivered: 2, 'In Transit': 2 } },
    'James Smith': { totalOrders: 4, statusCount: { 'In Transit': 1, Delivered: 3 } }
  }
  Order Type Count: { Online: 10, 'Dine In': 10 }